WebAutoPark/WebAutoPark/Controllers/VehicleStatusesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebAutoPark.Data;
using WebAutoPark.Data.Entities;
using WebAutoPark.Models.VehicleStatus;

namespace WebAutoPark.Controllers;

public class VehicleStatusesController : Controller
{
    private readonly AppAutoParkContext _context;
    private readonly IMapper _mapper;

    public VehicleStatusesController(AppAutoParkContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    public IActionResult Index()
    {
        var model = _mapper.ProjectTo<VehicleStatusItemVM>(_context.VehicleStatuses).ToList();
        return View(model);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost] 
    public async Task<IActionResult> Create(VehicleStatusCreateVM model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        var entity = _mapper.Map<VehicleStatusEntity>(model);
        await _context.VehicleStatuses.AddAsync(entity);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [HttpGet] //Тепер він працює методом GET - це щоб побачити форму
    public async Task<IActionResult> Edit(int id)
    {
        var entity = await _context.VehicleStatuses.FindAsync(id);
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<VehicleStatusEditVM>(entity);
        return View(model);
    }

    [HttpPost] //Тепер він працює методом GET - це щоб побачити форму
    public async Task<IActionResult> Edit(VehicleStatusEditVM model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var existing = await _context.VehicleStatuses.FirstOrDefaultAsync(x => x.Id == model.Id);
        if (existing == null)
        {
            return NotFound();
        }

        var duplicate = await _context.VehicleStatuses
            .FirstOrDefaultAsync(x => x.Name == model.Name && x.Id != model.Id);
        if (duplicate != null)
        {
            ModelState.AddModelError("Name", "Інший статус з такою назвою вже існує");
            return View(model);
        }

        existing = _mapper.Map(model, existing);

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id)
    {
        var item = await _context.VehicleStatuses.SingleOrDefaultAsync(x => x.Id == id);
        if (item != null)
        {
            _context.VehicleStatuses.Remove(item);
            await _context.SaveChangesAsync();
        }
        return RedirectToAction(nameof(Index));
    }

}

WebAutoPark/WebAutoPark/Controllers/VehiclesController.cs
using System;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebAutoPark.Data;
using WebAutoPark.Data.Entities;
using WebAutoPark.Helpers;
using WebAutoPark.Models.Company;
using WebAutoPark.Models.Vehicle;
using WebAutoPark.Models.VehicleStatus;

namespace WebAutoPark.Controllers;

public class VehiclesController : Controller
{
    private readonly AppAutoParkContext _context;
    private readonly IMapper _mapper;

    public VehiclesController(AppAutoParkContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    public IActionResult Index()
    {
        var model = _mapper.ProjectTo<VehicleItemVM>(_context.Vehicles).ToList();
        return View(model);
    }

    [HttpGet]
    public IActionResult Create()
    {
        VehicleCreateVM model = new VehicleCreateVM();
        model.Companies = _mapper.ProjectTo<SelectItemViewModel>(_context.Companies)
            .ToList();

        model.VehicleStatuses = _mapper.ProjectTo<SelectItemViewModel>(_context.VehicleStatuses)
            .ToList();

        return View(model);
    }

    [HttpPost] 
    public async Task<IActionResult> Create(VehicleCreateVM requestModel)
    {
        if (!ModelState.IsValid)
        {
            requestModel.Companies = _mapper.ProjectTo<SelectItemViewModel>(_context.Companies)
                .ToList();

            requestModel.VehicleStatuses = _mapper.ProjectTo<SelectItemViewModel>(_context.VehicleStatuses)
                .ToList();

            return View(requestModel);
        }
        var entity = _mapper.Map<VehicleEntity>(requestModel);
        await _context.Vehicles.AddAsync(entity);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));

    }

    [HttpGet] //Тепер він працює методом GET - це щоб побачити форму
    public async Task<IActionResult> Edit(int id)
    {
        var entity = await _context.Vehicles.FindAsync(id);
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<VehicleEditVM>(entity);

        model.Companies = _mapper.ProjectTo<SelectItemViewModel>(_context.Companies)
            .ToList();

        model.VehicleStatuses = _mapper.ProjectTo<SelectItemViewModel>(_context.VehicleStatuses)
            .ToList();

        return View(model);
    }

    [HttpPost] //Тепер він працює методом GET - це щоб побачити форму
    public async Task<IActionResult> Edit(VehicleEditVM requestModel)
    {
        if (!ModelState.IsValid)
        {
            requestModel.Companies = _mapper.ProjectTo<SelectItemViewModel>(_context.Companies)
                .ToList();

            requestModel.VehicleStatuses = _mapper.ProjectTo<SelectItemViewModel>(_context.VehicleStatuses)
                .ToList();
            return View(requestModel);
        }

        var existing = await _context.Vehicles.FirstOrDefaultAsync(x => x.Id == requestModel.Id);
        if (existing == null)
        {
            return NotFound();
        }


        existing = _mapper.Map(requestModel, existing);

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id)
    {
        var item = await _context.Vehicles.SingleOrDefaultAsync(x => x.Id == id);
        if (item != null)
        {
            _context.Vehicles.Remove(item);
            await _context.SaveChangesAsync();
        }
        return RedirectToAction(nameof(Index));
    }

}

WebAutoPark/WebAutoPark/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAutoPark</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAutoPark.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Автопарк</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Компанії</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleStatuses" asp-action="Index">Статуси Авто</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">Автомобілі</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebAutoPark - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>